### ISSUE TITLE
Bug in #2

### ISSUE THREAD

**Issue by sugarfi** [sugarfi/wicker#3]
@monarrk Looks like the exec support added in #2 is slightly broken - it doesn't seem to pass any flags to the command. Arguments work fine. Example:
Input: `ls -l`
Expected:
```
total 40
-rw-r--r-- 1 sugarfi root  19805 Dec  7 11:28 Cargo.lock
-rw-r--r-- 1 sugarfi root    296 Dec  7 11:27 Cargo.toml
-rw-r--r-- 1 sugarfi users  1395 Dec  7 14:40 README.md
drwxr-xr-x 4 sugarfi root   4096 Dec  7 17:04 src
drwxr-xr-x 3 sugarfi users  4096 Dec  7 11:14 target
-rw-r--r-- 1 sugarfi users   398 Dec  7 15:20 TODO
```
Actual:
```
Cargo.lock  Cargo.toml	README.md  src	target	TODO
```

**Comment by sugarfi** [comment]
just realized my directory ownership is messed up - ignore plz  '^^

**Comment by monarrk** [comment]
ah ok, I'm looking into it right now. I really out to have tested that again after reworking it huh

**Comment by monarrk** [comment]
ohhh this is because of the way args are parsed. because you pass in any args starting with - as a flag, it doesn't count as an argument. I'm gonna figure out how to fix this

**Comment by sugarfi** [comment]
ok
